"""empty message

Revision ID: 986beacbf00b
Revises: 5d86efc5c732
Create Date: 2023-05-09 11:01:04.415295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986beacbf00b'
down_revision = '5d86efc5c732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
